### ISSUE TITLE
Memory leak in longrunning processes

### ISSUE THREAD

**Issue by tymonTe** [phpro/annotated-cache-bundle#1]
Hi.

Thanks for creating the bundle.
I found one issue with it when using it in "longrunning" processes. In the services.yml, you're registering `MemoryResultCollector` as the default collector. While in the annotated-cache documentation, it states: 
> By default, a dummy collector will be used that doesn't collect anything

The consequence is that every result from redis is kept in memory forever.

I patched the issue in my project by creating an override:

```
class AnnotatedCacheBundleMemoryLeakFix implements CompilerPassInterface
{
    public function process(ContainerBuilder $container)
    {
        $memoryCollector = $container->getDefinition('phpro.annotated_cache.result_collector.memory');
        $memoryCollector->setClass(NullResultCollector::class);
    }
}
```

Cheers

**Comment by veewee** [comment]
Hi @batmaidTymon,

Thaks for reporting!
The cache package does indeed use a dummy collector. In this Symfony bundle however, we decided to use the in memory collector to display some stats in the developer toolbar.

The service with key `phpro.annotated_cache.result_collector.default` is being used which is an alias to the in memory collector `phpro.annotated_cache.result_collector.memory`.
You can change the alias to any service you want in the application configuration, as long as it is a `ResultCollectorInterface`. This way you don't need a compiler pass.

**Comment by tymonTe** [comment]
Hi. Thanks for the quick answer :)

I totally agree that its usefull to use the symfony developer bar. I'll tweak the config then to disable it only in the "prod" environment.
